-- Ordinary labels with verified native text/style update paths. Rich text is excluded.
return {
    DWW_Button_C={'Label'},
    WBP_Inventory_ItemTooltip_C={'DurationLabel','ItemLevelLabel','MainStatText','TimeCostLabel'},
    WBP_Inventory_ItemTooltip_WarningLabel_C={'Label'},
    WBP_Inventory_Item_C={'StackSizeLabel'},
    WBP_Inventory_LoadoutLabel_C={'Label'},
    WBP_Inventory_StatPanel_C={'CurrencyLabel'},
    WBP_Inventory_StatPanel_Details_C={'StatName'},
    WBP_Inventory_StatPanel_Stat_C={'NameLabel','ValueLabel'},
    WBP_Inventory_Stat_C={'StatNameLabel','StatValueLabel'},
    WBP_Journal_NewTimeline_Day_C={'DayLabel','TimeOfDayLabel'},
    WBP_Journal_QuestDescription_ActiveObjective_C={'DescriptionLabel','HeaderLabel'},
    WBP_Journal_QuestDescription_C={'DifficultyLabel','QuestDescriptionBox','QuestEndDescription','QuestNameLabel'},
    WBP_Journal_QuestDescription_PastObjective_C={'ObjectiveLabel'},
    WBP_Journal_QuestList_Category_C={'HeaderLabel'},
    WBP_Journal_QuestList_ObjectiveEntry_C={'ObjectiveNameLabel','SegmentCountLabel'},
    WBP_Journal_QuestList_QuestEntry_C={'QuestNameLabel'},
    WBP_Journal_Timeline_C={'DayCountLabel'},
    WBP_MainMenu_Button_C={'Label'},
    WBP_MainMenu_Button_DLC_C={'DLCWarningLabel'},
    WBP_Settings_Control_Slider_C={'ValueLabel'},
    WBP_Settings_Entry_C={'Label'},
    WBP_Settings_Panel_C={'SettingDescriptionLabel','SettingNameLabel'},
    WBP_Settings_PresetKeyDisplay_C={'Label'},
}
